# Generated by Django 4.1.7 on 2023-06-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_table',
            name='customer_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
