# Generated by Django 4.2.2 on 2023-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_query_crm_table_serving_crm_table_user_crm_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_crm_table',
            name='item_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
