# Generated by Django 4.2.2 on 2023-07-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_query_crm_table_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_crm_table',
            name='customer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
