# Generated by Django 4.2.2 on 2023-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_query_crm_table_customer_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serving_crm_table',
            name='category_cost',
        ),
        migrations.AddField(
            model_name='serving_crm_table',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
