# Generated by Django 4.2.2 on 2023-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_colour_item_view_serving_crm_table_checkout_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serving_crm_table',
            name='checkout_view',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
