# Generated by Django 4.2.2 on 2023-07-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_serving_crm_table_checkout_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serving_crm_table',
            old_name='checkout_view',
            new_name='cart_items_count',
        ),
        migrations.AddField(
            model_name='serving_crm_table',
            name='cart_items',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
