# Generated by Django 4.2.2 on 2023-08-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_query_crm_table_theme_count_query_crm_table_theme_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themefurniture',
            name='theme_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
