# Generated by Django 4.2.2 on 2023-08-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_themefurniture_theme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_crm_table',
            name='cancellations_customer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='query_crm_table',
            name='cancellations_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
